# -------------------------------------
# Production
# -------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.show_sql=false

logging.level.root=INFO
logging.level.com.joying=INFO
logging.level.org.hibernate.SQL=INFO

# Swagger
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

server.forward-headers-strategy=framework
server.tomcat.use-relative-redirects=true