# -------------------------------------
# 기본 애플리케이션 정보
# -------------------------------------
spring.application.name=Joying

# -------------------------------------
# 프로파일 설정
# -------------------------------------
spring.profiles.active=local

# -------------------------------------
# JPA 공통 설정
# -------------------------------------
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# -------------------------------------
# JSON 변환 설정
# -------------------------------------
spring.jackson.property-naming-strategy=SNAKE_CASE

# -------------------------------------
# 파일 업로드 설정
# -------------------------------------
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# -------------------------------------
# 기본 프로필 이미지 설정
# -------------------------------------
app.default-profile-image=/images/default_profile_image.png

# -------------------------------------
# 로깅 설정
# -------------------------------------
logging.level.org.hibernate.SQL=${LOGGING_LEVEL:info}

# -------------------------------------
# Swagger/OpenAPI 설정
# -------------------------------------
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.doc-expansion=none
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

# -------------------------------------
# cloudflare r2
# -------------------------------------
cloudflare.r2.endpoint=https://0c6053f6f25550f3e00981b567d30604.r2.cloudflarestorage.com
cloudflare.r2.bucket=joying
cloudflare.r2.access-key=ab39b93eb3be525563ac8fd47a9e1ac5
cloudflare.r2.secret-key=b3668c169f70a4734a53ad9798be7468238499a3eadf765eb6487b56b268302c
app.file.public-base-url: https://pub-ae135e3bc46443e1aae3c0bae55f45cc.r2.dev
